upstream strapi {
    server strapi:1337;
    keepalive 64;
}

server {
    listen 80;
    server_name vm4687830.firstbyte.club;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {

    listen 443 ssl http2;

    server_name vm4687830.firstbyte.club;

    ssl_certificate     /etc/letsencrypt/live/vm4687830.firstbyte.club/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vm4687830.firstbyte.club/privkey.pem;

    client_max_body_size 512M;

    location / {

        proxy_pass http://strapi;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location = /_health {
        proxy_pass http://strapi/_health;
        access_log off;
    }
}