/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import videoOptimizer from "@frkntmbs/strapi-plugin-video-optimizer/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiCustomActionPerformPage from "strapi-custom-action-perform-page/strapi-admin";
import iconsField from "strapi-plugin-icons-field/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "video-optimizer": videoOptimizer,
    "strapi-cloud": strapiCloud,
    documentation: documentation,
    "users-permissions": usersPermissions,
    "strapi-custom-action-perform-page": strapiCustomActionPerformPage,
    "icons-field": iconsField,
  },
});
